### PR TITLE
Adding few functions required by the new pronto redesign + some cleaning

### PR DESCRIPTION
**Pull request by mcamurri**

### CODE REVIEW

**Comment by benoit-robotics** [comment]
@mcamurri 
It seems that "pronto_lcmtypes" is missing : [build](http://ori-ci-gateway.robots.ox.ac.uk:10301/job/drs_pr_ori_drs_pronto_utils/132/consoleFull)

**Comment by mcamurri** [comment]
> @mcamurri
> It seems that "pronto_lcmtypes" is missing
> ["here"](http://ori-ci-gateway.robots.ox.ac.uk:10301/job/drs_pr_ori_drs_pronto_utils/132/consoleFull)

I'm looking into that thanks.

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
It doesn't work to add "catkin config --blacklist ... " at the end of clone_deps.sh as the commands that are inside this file are not executed ( I didn't put in place this system ), this file is only used to get the url of each repositories.
Why don't you remove the packages instead of trying to blacklist them ?

**Comment by mcamurri** [comment]
> It doesn't work to add "catkin config --blacklist ... " at the end of clone_deps.sh as the commands that are inside this file are not executed ( I didn't put in place this system ), this file is only used to get the url of each repositories.
> Why don't you remove the packages instead of trying to blacklist them ?

Yes I know that, it was just for the pronto_build workspace which is not built by the server, it is just for local computer testing.

With the super build it should work because all the missing repos are there (it works on my computer without blacklisting).

Anyways, I have to blacklist because the repo contains packages I need and packages I don't need. If I remove the packages I don't need from the repo, then other packages from the superbuild would fail.
Therefore I started moving LCM packages related to pronto [here](https://github.com/ori-drs/pronto_legacy).

**Comment by mcamurri** [comment]
[jenkins test this]

**Comment by mcamurri** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
the tests of pronto_estimator_lcm are  failing

**Comment by mcamurri** [comment]
> the tests of pronto_estimator_lcm are failing

I've fixed that, too.
It should be the last one.

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Comment by benoit-robotics** [comment]
[jenkins test this]

**Pull request merged**
